export default function TermsPage() {
  return (
    <main className="min-h-screen bg-stone-50 px-5 py-8 text-stone-900">
      <div className="mx-auto max-w-3xl rounded-3xl bg-white p-6 shadow-sm">
        <a
          href="/"
          className="mb-6 inline-block text-sm text-stone-500 hover:text-stone-800"
        >
          ← Back to Talkio
        </a>

        <h1 className="text-3xl font-semibold tracking-tight">
          Terms of Service
        </h1>

        <p className="mt-2 text-sm text-stone-500">
          Effective Date: May 10, 2026
        </p>

        <div className="mt-8 space-y-6 text-sm leading-7 text-stone-700">
          <section>
            <h2 className="text-lg font-semibold text-stone-900">1. Acceptance of Terms</h2>
            <p>
              By using Talkio, you agree to these Terms of Service. If you do not agree,
              please do not use the app or related services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">2. What Talkio Provides</h2>
            <p>
              Talkio is an AI-powered conversation companion designed for emotional support,
              reflection, grounding conversations, and general companionship. Talkio uses
              artificial intelligence to generate responses based on what you share.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">3. Not Medical, Therapy, or Emergency Care</h2>
            <p>
              Talkio is not a licensed therapist, doctor, counselor, medical provider,
              crisis service, or emergency service. Talkio does not provide medical advice,
              diagnosis, treatment, psychiatric care, therapy, or crisis intervention.
            </p>
            <p className="mt-3">
              If you are in immediate danger, experiencing a mental health emergency, or may
              harm yourself or someone else, contact local emergency services or a crisis
              hotline immediately. Do not rely on Talkio during emergencies.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">4. AI-Generated Responses</h2>
            <p>
              Talkio responses are generated by automated AI systems. AI responses may be
              incomplete, inaccurate, inappropriate, delayed, or misunderstood. You are
              responsible for how you interpret and use any information or support provided
              by Talkio.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">5. User Responsibility</h2>
            <p>
              You agree not to use Talkio to request, plan, encourage, or carry out harmful,
              abusive, illegal, deceptive, exploitative, or unsafe behavior. You remain
              responsible for your own decisions, actions, and interactions with others.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">6. Safety Features</h2>
            <p>
              Talkio may use automated safety systems to detect crisis language, harmful
              intent, abusive behavior, or unsafe interactions. In some cases, Talkio may
              limit, pause, redirect, or refuse certain conversations for safety reasons.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">7. Accounts and Access</h2>
            <p>
              Talkio may offer anonymous access, account-based access, free usage limits,
              and paid subscription plans. You are responsible for maintaining access to
              your account and device.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">8. Subscriptions and Payments</h2>
            <p>
              Paid features may be offered through Talkio Pro, Talkio Voice, or other plans.
              Subscription payments, renewals, cancellations, and refunds may be handled by
              Google Play or another payment provider according to their terms and policies.
              Talkio does not store your full payment card information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">9. Acceptable Use</h2>
            <p>
              You may not use Talkio to harass, threaten, exploit, deceive, manipulate,
              impersonate, abuse, or harm others. You may not attempt to reverse engineer,
              disrupt, overload, scrape, or misuse Talkio systems.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">10. Privacy</h2>
            <p>
              Your use of Talkio is also governed by our Privacy Policy, available at
              https://talkiochat.com/privacy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">11. Service Availability</h2>
            <p>
              Talkio may be unavailable, delayed, limited, or interrupted due to maintenance,
              technical issues, third-party service outages, model provider issues, quota
              limits, or other circumstances.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Talkio and its operators are not liable
              for indirect, incidental, consequential, special, or punitive damages, or for
              decisions or actions you take based on AI-generated responses.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">13. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Updated versions will be posted at
              https://talkiochat.com/terms. Continued use of Talkio after updates means you
              accept the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-stone-900">14. Contact</h2>
            <p>
              For questions about these Terms, contact Talkio Support at support@talkiochat.com.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}